spring:
    profiles:
        active: dev

    datasource:
        driver-class-name: org.h2.Driver
        username: sa
        password:
        url: jdbc:h2:mem:testdb

    security:
        user:
            name: admin
            password: pruebaAdmin12#.$

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus



